services:
  - type: web
    name: public-safety-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot.app:app --host 0.0.0.0 --port 8000 --workers 4

  - type: web
    name: indiana-safety-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 8501
    envVars:
      - key: FASTAPI_URL
        value: https://public-safety-bot.onrender.com